name: Python Script Workflow

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose the operating system you prefer

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install any required Python packages

    - name: Run Python script
      run: |
        mkdir -p converted_files
        python actions.py
      working-directory: ${{ github.workspace }}
      
    - name: List files for debugging
      run: |
        echo "Files in the workspace:"
        ls -R
      working-directory: ${{ github.workspace }}
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git status
        git commit -m "Add converted files" || echo "No changes to commit"
      working-directory: ${{ github.workspace }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
